---
title: "PredictorVariables"
author: "Melissa M. Rohde"
date: "2023-04-25"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(ggplot2)
library(gridExtra)
library(overlapping)
library(stringr)
library(dplyr)
library(here)
```

## Load Data


```{r pressure, echo=FALSE}

training1 <- read.csv(here('data/TrainingData_withpredictors/trainingpts1_withpredictors.csv'))
training2 <- read.csv(here('data/TrainingData_withpredictors/trainingpts2_withpredictors.csv'))
training3 <- read.csv(here('data/TrainingData_withpredictors/trainingpts3_withpredictors.csv'))
training4 <- read.csv(here('data/TrainingData_withpredictors/trainingpts4_withpredictors.csv'))
training5 <- read.csv(here('data/TrainingData_withpredictors/trainingpts5_withpredictors.csv'))
training6 <- read.csv(here('data/TrainingData_withpredictors/trainingpts6_withpredictors.csv'))
training7 <- read.csv(here('data/TrainingData_withpredictors/trainingpts7_withpredictors.csv'))
training8 <- read.csv(here('data/TrainingData_withpredictors/trainingpts8_withpredictors.csv'))
validation1 <- read.csv(here('data/TrainingData_withpredictors/validationpts1_withpredictors.csv'))
validation2 <- read.csv(here('data/TrainingData_withpredictors/validationpts2_withpredictors.csv'))

training <- rbind(training1,training2,training3,training4,training5,training6,training7,training8,validation1,validation2)

global1 <- read.csv(here('data/RandomPointsGlobalGDE/globalvalpts1_withpredictors.csv'))
global2 <- read.csv(here('data/RandomPointsGlobalGDE/globalvalpts2_withpredictors.csv'))
global3 <- read.csv(here('data/RandomPointsGlobalGDE/globalvalpts3_withpredictors.csv'))
global4 <- read.csv(here('data/RandomPointsGlobalGDE/globalvalpts4_withpredictors.csv'))
global5 <- read.csv(here('data/RandomPointsGlobalGDE/globalvalpts5_withpredictors.csv'))
global <- rbind(global1,global2,global3,global4,global5)

```

## Run Modified Code from Overlapping R package, so that data output can be returned instead of a plot.

```{r}
# Downloaded from https://www.rdocumentation.org/packages/overlapping/versions/2.1
source('ovmult.R')
source('overlap_revised.R')
```


## Extract latitudes from training and global points
```{r}
global_coord <- read.csv('data/RandomPointsGlobalGDE/globalvalPts.csv') %>%
              right_join(global, by="id") %>%
              select(.geo.x) %>%
              mutate(coord = str_sub(.geo.x,32,-3))
              
global_latitude<- as.numeric(data.frame(do.call('rbind',strsplit(as.character(global_coord$coord),',',fixed=TRUE)))[,2])
              

training_coord <- read.csv('data/TrainingData_withpredictors/jointrain.csv') %>%
                  rbind(read.csv('data/TrainingData_withpredictors/joinval.csv')) %>%
                  select(.geo) %>%
                  mutate(coord = str_sub(.geo,32,-3))

training_latitude<- as.numeric(data.frame(do.call('rbind',strsplit(as.character(training_coord$coord),',',fixed=TRUE)))[,2])

```


## Run Overlapping package to retrieve overlap statistics, and plot Global and Training dataset distributions for each predictor variable

```{r}
## CTI ##
dataList <- list(Global=global$CTI, Training = training$CTI )
CTI_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p1<- ggplot() + theme_bw() + ylab("Density") + xlab("CTI") + ggtitle(paste("a. ",as.character(round(CTI_stat$OV,2)),sep="")) +
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


## LST ##
dataList <- list(Global = global$lst_tpi5400,Training =training$lst_tpi5400)
LST_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p2<- ggplot() + theme_bw() + ylab("Density") + xlab("LST") + ggtitle(paste("b. ",as.character(round(LST_stat$OV,2)),sep="")) + 
 ylim(0,0.8) + xlim(-10,10) +
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold"))

## ETaP ##
dataList <- list(Global = global$ETaP,Training=training$ETaP)
ETaP_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p3<- ggplot() + theme_bw() + ylab("Density") + xlab("ETaP") + xlim(0,0.15) +ylim(0,60) +
  ggtitle(paste("c. ",as.character(round(ETaP_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 

## msavi ##
dataList <- list(Global = global$msavi,Training = training$msavi)
msavi_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p4<- ggplot() + theme_bw() + ylab("Density") + xlab("MSAVI - Annual") + ylim(0,12) + xlim(0,0.5) +
  ggtitle(paste("d. ",as.character(round(msavi_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


## msavi_cv ##
dataList <- list(Global =global$msavi_cv,Training = training$msavi_cv)
msavi_cv_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p5<- ggplot() + theme_bw() + ylab("Density") + xlab("MSAVI_CV") + xlim(-0.25,0.5) + ylim(0,8) +
  ggtitle(paste("e. ",as.character(round(msavi_cv_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 



## ndvi ##
dataList <- list(Global =global$ndvi,Training=training$ndvi)
ndvi_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p6<-ggplot() + theme_bw() + ylab("Density") + xlab("NDVI - Annual")  + xlim(0,1)+ ylim(0,8) +
  ggtitle(paste("f. ",as.character(round(ndvi_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


## ndvi_cv ##
dataList <- list(Global =global$ndvi_cv,Training =training$ndvi_cv)
ndvi_cv_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p7<-ggplot() + theme_bw() + ylab("Density") + xlab("NDVI_CV") + xlim(-0.25,0.5) + ylim(0,8) +
  ggtitle(paste("g. ",as.character(round(ndvi_cv_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold"))




## ndwi_leaf ##
dataList <- list(Global =global$ndwi_leaf,Training =training$ndwi_leaf)
ndwi_leaf_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p8<- ggplot() + theme_bw() + ylab("Density") + xlab("NDWI_Leaf - Annual") +  xlim(-0.5,0.5)+ylim(0,10) +
  ggtitle(paste("h. ",as.character(round(ndwi_leaf_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 

## ndwi_leaf_cv ##
dataList <- list(Global =global$ndwi_leaf_cv,Training =training$ndwi_leaf_cv)
ndwi_leaf_cv_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p9<- ggplot() + theme_bw() + ylab("Density") + xlab("NDWI_Leaf_CV") + xlim(-0.5,1)+ ylim(0,8) +
  ggtitle(paste("i. ",as.character(round(ndwi_leaf_cv_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


## ndwi_water ##
dataList <- list(Global =global$ndwi_water,Training =training$ndwi_water)
ndwi_water_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p10<- ggplot() + theme_bw() + ylab("Density") + xlab("NDWI_Water - Annual") + xlim(-1,0)+# ylim(0,10) +
  ggtitle(paste("j. ",as.character(round(ndwi_water_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


## ndwi_water_cv ##
dataList <- list(Global =global$ndwi_water_cv,Training=training$ndwi_water_cv)
ndwi_water_cv_stat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p11<- ggplot() + theme_bw() + ylab("Density") + xlab("NDWI_Water_CV") +  xlim(-0.3,0.1)+ ylim(0,15) +
  ggtitle(paste("k. ",as.character(round(ndwi_water_cv_stat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) 


# -- Latitude -- #
dataList <- list(Global =global_latitude,Training= training_latitude) 
latitudeStat <- overlap(dataList,plot=FALSE)
df<- overlap_revised(dataList, plot=TRUE)
g <- data.frame(df$Global)
t <- data.frame(df$Training)

p12<- ggplot() + theme_bw() + ylab("Density") + xlab("Latitude") +
  ggtitle(paste("l. ",as.character(round(latitudeStat$OV,2)),sep="")) + 
  geom_density(data=g,aes(x=df.Global), color="blue", fill="blue",alpha = 0.5) + 
  geom_density(data=t,aes(x=df.Training), color="red", fill='red',alpha=0.5) + 
  theme(axis.text = element_text(size=14, face="bold"),
        axis.title = element_text(size=14, face="bold"),
        plot.title = element_text(size=18, face="bold")) +
  scale_x_continuous(breaks=c(-60,-45,-30,-15,0,15,30,45,60), limits=c(-60,60))


fig<- grid.arrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,nrow=4)


ggsave(filename = "OverlapStats_Predictors.png",
        plot = fig, 
        device="png",
        height=8.5, 
        width=11, 
        units= "in")

```